/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FloridaSolarPermitLawRouteImport } from './routes/florida-solar-permit-law'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolarDetachAndResetRouteImport } from './routes/solar-detach-and-reset'
import { Route as SolarPanelRemovalCostRouteImport } from './routes/solar-panel-removal-cost'
import { Route as CountiesIndexRouteImport } from './routes/counties.index'
import { Route as CountiesCountyRouteImport } from './routes/counties.$county'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as SolarCompanyOutOfBusinessIndexRouteImport } from './routes/solar-company-out-of-business.index'
import { Route as SolarCompanyOutOfBusinessBrandRouteImport } from './routes/solar-company-out-of-business.$brand'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FloridaSolarPermitLawRoute = FloridaSolarPermitLawRouteImport.update({
  id: '/florida-solar-permit-law',
  path: '/florida-solar-permit-law',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarDetachAndResetRoute = SolarDetachAndResetRouteImport.update({
  id: '/solar-detach-and-reset',
  path: '/solar-detach-and-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarPanelRemovalCostRoute = SolarPanelRemovalCostRouteImport.update({
  id: '/solar-panel-removal-cost',
  path: '/solar-panel-removal-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesIndexRoute = CountiesIndexRouteImport.update({
  id: '/counties/',
  path: '/counties/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesCountyRoute = CountiesCountyRouteImport.update({
  id: '/counties/$county',
  path: '/counties/$county',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/service-areas/$city',
  path: '/service-areas/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarCompanyOutOfBusinessIndexRoute =
  SolarCompanyOutOfBusinessIndexRouteImport.update({
    id: '/solar-company-out-of-business/',
    path: '/solar-company-out-of-business/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolarCompanyOutOfBusinessBrandRoute =
  SolarCompanyOutOfBusinessBrandRouteImport.update({
    id: '/solar-company-out-of-business/$brand',
    path: '/solar-company-out-of-business/$brand',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/florida-solar-permit-law': typeof FloridaSolarPermitLawRoute
  '/leads': typeof LeadsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-detach-and-reset': typeof SolarDetachAndResetRoute
  '/solar-panel-removal-cost': typeof SolarPanelRemovalCostRoute
  '/counties/$county': typeof CountiesCountyRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/solar-company-out-of-business/$brand': typeof SolarCompanyOutOfBusinessBrandRoute
  '/counties/': typeof CountiesIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solar-company-out-of-business/': typeof SolarCompanyOutOfBusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/florida-solar-permit-law': typeof FloridaSolarPermitLawRoute
  '/leads': typeof LeadsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-detach-and-reset': typeof SolarDetachAndResetRoute
  '/solar-panel-removal-cost': typeof SolarPanelRemovalCostRoute
  '/counties/$county': typeof CountiesCountyRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/solar-company-out-of-business/$brand': typeof SolarCompanyOutOfBusinessBrandRoute
  '/counties': typeof CountiesIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
  '/solar-company-out-of-business': typeof SolarCompanyOutOfBusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/florida-solar-permit-law': typeof FloridaSolarPermitLawRoute
  '/leads': typeof LeadsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-detach-and-reset': typeof SolarDetachAndResetRoute
  '/solar-panel-removal-cost': typeof SolarPanelRemovalCostRoute
  '/counties/$county': typeof CountiesCountyRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/solar-company-out-of-business/$brand': typeof SolarCompanyOutOfBusinessBrandRoute
  '/counties/': typeof CountiesIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solar-company-out-of-business/': typeof SolarCompanyOutOfBusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/florida-solar-permit-law'
    | '/leads'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/solar-detach-and-reset'
    | '/solar-panel-removal-cost'
    | '/counties/$county'
    | '/service-areas/$city'
    | '/services/$service'
    | '/solar-company-out-of-business/$brand'
    | '/counties/'
    | '/service-areas/'
    | '/services/'
    | '/solar-company-out-of-business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/florida-solar-permit-law'
    | '/leads'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/solar-detach-and-reset'
    | '/solar-panel-removal-cost'
    | '/counties/$county'
    | '/service-areas/$city'
    | '/services/$service'
    | '/solar-company-out-of-business/$brand'
    | '/counties'
    | '/service-areas'
    | '/services'
    | '/solar-company-out-of-business'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/florida-solar-permit-law'
    | '/leads'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/solar-detach-and-reset'
    | '/solar-panel-removal-cost'
    | '/counties/$county'
    | '/service-areas/$city'
    | '/services/$service'
    | '/solar-company-out-of-business/$brand'
    | '/counties/'
    | '/service-areas/'
    | '/services/'
    | '/solar-company-out-of-business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FloridaSolarPermitLawRoute: typeof FloridaSolarPermitLawRoute
  LeadsRoute: typeof LeadsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarDetachAndResetRoute: typeof SolarDetachAndResetRoute
  SolarPanelRemovalCostRoute: typeof SolarPanelRemovalCostRoute
  CountiesCountyRoute: typeof CountiesCountyRoute
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  SolarCompanyOutOfBusinessBrandRoute: typeof SolarCompanyOutOfBusinessBrandRoute
  CountiesIndexRoute: typeof CountiesIndexRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SolarCompanyOutOfBusinessIndexRoute: typeof SolarCompanyOutOfBusinessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florida-solar-permit-law': {
      id: '/florida-solar-permit-law'
      path: '/florida-solar-permit-law'
      fullPath: '/florida-solar-permit-law'
      preLoaderRoute: typeof FloridaSolarPermitLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-detach-and-reset': {
      id: '/solar-detach-and-reset'
      path: '/solar-detach-and-reset'
      fullPath: '/solar-detach-and-reset'
      preLoaderRoute: typeof SolarDetachAndResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-panel-removal-cost': {
      id: '/solar-panel-removal-cost'
      path: '/solar-panel-removal-cost'
      fullPath: '/solar-panel-removal-cost'
      preLoaderRoute: typeof SolarPanelRemovalCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties/': {
      id: '/counties/'
      path: '/counties'
      fullPath: '/counties/'
      preLoaderRoute: typeof CountiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties/$county': {
      id: '/counties/$county'
      path: '/counties/$county'
      fullPath: '/counties/$county'
      preLoaderRoute: typeof CountiesCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/service-areas/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-company-out-of-business/': {
      id: '/solar-company-out-of-business/'
      path: '/solar-company-out-of-business'
      fullPath: '/solar-company-out-of-business/'
      preLoaderRoute: typeof SolarCompanyOutOfBusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-company-out-of-business/$brand': {
      id: '/solar-company-out-of-business/$brand'
      path: '/solar-company-out-of-business/$brand'
      fullPath: '/solar-company-out-of-business/$brand'
      preLoaderRoute: typeof SolarCompanyOutOfBusinessBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FloridaSolarPermitLawRoute: FloridaSolarPermitLawRoute,
  LeadsRoute: LeadsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarDetachAndResetRoute: SolarDetachAndResetRoute,
  SolarPanelRemovalCostRoute: SolarPanelRemovalCostRoute,
  CountiesCountyRoute: CountiesCountyRoute,
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  SolarCompanyOutOfBusinessBrandRoute: SolarCompanyOutOfBusinessBrandRoute,
  CountiesIndexRoute: CountiesIndexRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SolarCompanyOutOfBusinessIndexRoute: SolarCompanyOutOfBusinessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
